// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwr0IWHw7bbW-JMEpj9HpJzo62Asz885o',
    appId: '1:639685857613:web:ae65bf486464ef36cce704',
    messagingSenderId: '639685857613',
    projectId: 'pedalcapp-52f63',
    authDomain: 'pedalcapp-52f63.firebaseapp.com',
    storageBucket: 'pedalcapp-52f63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpzo6uZkv0jH8SRDCwPNSs9D3X61GJTeY',
    appId: '1:639685857613:android:340392f63aca453dcce704',
    messagingSenderId: '639685857613',
    projectId: 'pedalcapp-52f63',
    storageBucket: 'pedalcapp-52f63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgddzgbDoHOfV8hFTqW3fRYRFgK7OR4SQ',
    appId: '1:639685857613:ios:0afc81011d61d638cce704',
    messagingSenderId: '639685857613',
    projectId: 'pedalcapp-52f63',
    storageBucket: 'pedalcapp-52f63.appspot.com',
    iosBundleId: 'com.example.pointATob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgddzgbDoHOfV8hFTqW3fRYRFgK7OR4SQ',
    appId: '1:639685857613:ios:0afc81011d61d638cce704',
    messagingSenderId: '639685857613',
    projectId: 'pedalcapp-52f63',
    storageBucket: 'pedalcapp-52f63.appspot.com',
    iosBundleId: 'com.example.pointATob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwr0IWHw7bbW-JMEpj9HpJzo62Asz885o',
    appId: '1:639685857613:web:3ce1944878900221cce704',
    messagingSenderId: '639685857613',
    projectId: 'pedalcapp-52f63',
    authDomain: 'pedalcapp-52f63.firebaseapp.com',
    storageBucket: 'pedalcapp-52f63.appspot.com',
  );

}